### ISSUE TITLE
[BUG] UnsupportetAssetException after init and fetch

### ISSUE THREAD

**Issue by abach42** [CPS-IT/frontend-asset-handler#129]
### PHP version

8.1

### Composer version

latest

### Package version

2.0.0

### Application

Composer

### Operating system

OS/2

### Current behavior

In UnsupportedAssetException.php line 39:
                                                                                                                     
  [CPSIT\FrontendAssetHandler\Exception\UnsupportedAssetException (1623922009)]                                      
  The asset with source "{"type":"http","url":"https:\/\/static.basic.zug.321.works\/latest.tar.gz","environment":"  
  fe-feature-core_upgrade_10_4-11_5","revision":null}" and target "{"type":"archive","revision-file":"REVISION","pa  
  th":"app\/web\/assets\/zug-frontend\/base","base":"dist\/"}" is not supported. 

### Steps to reproduce

/var/www/html$ app/vendor/bin/frontend-assets init
/var/www/html$ app/vendor/bin/frontend-assets fetch 

### Additional context

Exception trace:
  at /var/www/html/app/vendor/cpsit/frontend-asset-handler/src/Exception/UnsupportedAssetException.php:39
 CPSIT\FrontendAssetHandler\Exception\UnsupportedAssetException::create() at /var/www/html/app/vendor/cpsit/frontend-asset-handler/src/Processor/FileArchiveProcessor.php:193
 CPSIT\FrontendAssetHandler\Processor\FileArchiveProcessor->determineType() at /var/www/html/app/vendor/cpsit/frontend-asset-handler/src/Processor/FileArchiveProcessor.php:158
 CPSIT\FrontendAssetHandler\Processor\FileArchiveProcessor->openArchive() at /var/www/html/app/vendor/cpsit/frontend-asset-handler/src/Processor/FileArchiveProcessor.php:95
 CPSIT\FrontendAssetHandler\Processor\FileArchiveProcessor->processAsset() at /var/www/html/app/vendor/cpsit/frontend-asset-handler/src/Handler/AssetHandler.php:90
 CPSIT\FrontendAssetHandler\Handler\AssetHandler->handle() at /var/www/html/app/vendor/cpsit/frontend-asset-handler/src/Command/FetchAssetsCommand.php:181
 CPSIT\FrontendAssetHandler\Command\FetchAssetsCommand->performAssetHandling() at /var/www/html/app/vendor/cpsit/frontend-asset-handler/src/Command/FetchAssetsCommand.php:155
 CPSIT\FrontendAssetHandler\Command\FetchAssetsCommand->execute() at /var/www/html/app/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /var/www/html/app/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/app/vendor/cpsit/frontend-asset-handler/src/Console/Application.php:98
 CPSIT\FrontendAssetHandler\Console\Application->doRunCommand() at /var/www/html/app/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /var/www/html/app/vendor/cpsit/frontend-asset-handler/src/Console/Application.php:84
 CPSIT\FrontendAssetHandler\Console\Application->doRun() at /var/www/html/app/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /var/www/html/app/vendor/cpsit/frontend-asset-handler/bin/frontend-assets:57
 include() at /var/www/html/app/vendor/bin/frontend-assets:120

**Comment by eliashaeussler** [comment]
Hi @abach42, thanks for the issue. This is now fixed and released as `2.0.1`.
