### ISSUE TITLE
[BUG] Failed download ends with exit code zero

### ISSUE THREAD

**Issue by eliashaeussler** [CPS-IT/frontend-asset-handler#193]
### PHP version

8.1.16

### Composer version

2.5.1

### Package version

1.4.0

### Application

Composer

### Operating system

macOS 13.2.1

### Current behavior

When downloading a non-existent asset, an error is shown (which is correct). However, the command does not exit with a non-zero code:

```bash
$ composer exec frontend-assets fetch integration

Running Frontend Asset Handler 1.4.0 #StandWithUkraine
------------------------------------------------------

Project branch: integration
Asset environment: integration
Source url: xxx
Downloading assets... Failed

                                                                                                                        
 [ERROR] The requested URL "xxx" is not available (Error 404).        
                                                                                                                        

$ echo $?                                                                                            
0
```

### Expected behavior

Whenever a failure occurs, the application should exit with a non-zero exit code.

### Steps to reproduce

1. Run `frontend-assets fetch` on an unavailable asset environment
2. Check the exit code with `echo $?`

**Comment by eliashaeussler** [comment]
@mteu Do you think this can be related to #40?

**Comment by mteu** [comment]
I sure hope not. I'll check, though. Thanks for bringing the issue to my attention.

**Comment by eliashaeussler** [comment]
Ah, the issue seems to be with this line:

https://github.com/CPS-IT/frontend-asset-handler/blob/ec70a2694d39c4327183a047ebac7a07efefc1ca/src/Command/FetchAssetsCommand.php#L160

If only one asset definition is configured (which means `$assetCount === 1`), the condition is never met.
