### ISSUE TITLE
[FEATURE] apply default value for target.type

### ISSUE THREAD

**Issue by dwenzel** [CPS-IT/frontend-asset-handler#22]
### Is your feature request related to a problem?

The documentation for `target.type` states 

> Required: `yes`
> Default: `archive` (resolves to [FileArchiveProcessor](https://github.com/CPS-IT/frontend-asset-handler/blob/main/src/Processor/FileArchiveProcessor.php))

If the key is not present, an error occurs
```
In InvalidConfigurationException.php line 59:
                                                                       
  The configuration is invalid:                                        
    * [/frontend-assets/0/target/type]: The property type is required  
```

### Describe the solution you'd like

I would prefer, if the default value `archive` were applied _without_ any configuration. 

This way less configuration were necessary.

**Comment by eliashaeussler** [comment]
@dwenzel Thanks for the issue. This is now resolved with the latest version `1.0.2`, see #24.
