### ISSUE TITLE
[BUG] allow to fetch a specific Version failed

### ISSUE THREAD

**Issue by IngoMueller** [CPS-IT/frontend-asset-handler#42]
### PHP version

8.1

### Composer version

2.4.2

### Package version

1.0.3

### Application

Composer

### Operating system

Apache

### Current behavior

Dear Elias,

i configure in assets.json following lines to fetch a specific Tag of frontend:

`"environments": {
      "map": {
	      "*": {
		      "transformer": "version"
	      }
      }
}`

i got always the stable Version, not the tagged-Version

What i do wrong?
Thanks, Ingo

**Comment by eliashaeussler** [comment]
Hi @IngoMueller, thanks for your issue. This is now resolved with `1.1.0`.

**Comment by IngoMueller** [comment]
Hey @eliashaeussler, thanks for take care of this issue. Works fine for me now
